### ISSUE TITLE
The version 2 is not workable when variant videos/options on.

### ISSUE THREAD

**Issue by RyanChuang** [JonnyShuali/netdna-storage-click-bypass#2]
The current version of this script is not compatible wherein variant of videos/options is on the webpage,it kept reloading could not stop. Even though you have clicked one option it kept rolled back to the original.  Please fix this issue. Thank you. The first version is fine,
 https://ibb.co/cYE3Ha

**Comment by mickcarterus** [comment]
Add this line at the beginning 
// @exclude       *://netdna-storage.com/download/*

That should fix it.

**Comment by RyanChuang** [comment]
Thank you. It works now.

**Comment by RyanChuang** [comment]
It did work,however it couldn't download right away without pop-ups which is inconvenience. I will stick with v.1 unless otherwise.  Thanks for solutions anyway.

**Comment by JonnyShuali** [comment]
Hey, sorry for the delay. I released a new version. It should work fine now.

**Comment by JonnyShuali** [comment]
Sorry, the patch I released was only working on Firefox. Now it works all platforms again :) .

**Comment by RyanChuang** [comment]
Thank you. It work now.

**Comment by RyanChuang** [comment]
Hi,Jonny Shuali
The version 4 is still has pop-ups issue when clicked the Download button,it just couldn't execute the process but kept looping pop-ups. And again,version 1 is fine.

**Comment by JonnyShuali** [comment]
You shouldn't click on the Download button. It suppose to click it by itself.
What browser and plugin are you using? Can you take a video so I can see the problem?

**Comment by RyanChuang** [comment]
I think I found the problem.

**Comment by RyanChuang** [comment]
I think I found the problem;on that webpage,I didn't block adf.ly which why it kept pop-ups. Now,it solved. Thank you for this good script. Regarding automatically kick-in of Download button,it didn't. Yet,I am fine with that since I always choose other options than the Original file. My gig is Vivaldi (Chrome based),uBlock origin,uMatrix,Tampermonkey(with AdsBypasser script).
